name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build-using-gnu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake --preset CI-g++
    - name: Build
      run: cmake --build ${{github.workspace}}/build/g++ -v -j $(nproc)
    - name: Test
      run: ctest --test-dir ${{github.workspace}}/build/g++/
    - name: Install
      run: sudo cmake --install ${{github.workspace}}/build/g++/

  build-using-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake --preset CI-clang++
    - name: Build
      run: cmake --build ${{github.workspace}}/build/clang++ -v -j $(nproc)
    - name: Test
      run: ctest --test-dir ${{github.workspace}}/build/clang++/
    - name: Install
      run: sudo cmake --install ${{github.workspace}}/build/clang++/

  dynamic-analysis-using-valgrind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Valgrind
      run: |
          sudo apt-get update
          sudo apt install -y valgrind
    - name: Configure CMake
      run: cmake --preset CI-g++
    - name: Build
      run: cmake --build ${{github.workspace}}/build/g++ -v -j $(nproc)
    - name: Test with Valgrind
      run: ctest -T memcheck --test-dir ${{github.workspace}}/build/g++/ --output-on-failure -VV

  static-analysis-using-clang-tidy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake --preset CI-clang-tidy
    - name: Build
      run: cmake --build ${{github.workspace}}/build/clang-tidy -v -j $(nproc)

  code-coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Install lcov
      run: |
          sudo apt-get update
          sudo apt install -y lcov
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake --preset CI-code-coverage
    - name: Build
      run: cmake --build ${{github.workspace}}/build/code-coverage -v -j $(nproc)
    - name: Test
      run: ctest --test-dir ${{github.workspace}}/build/code-coverage
    - name: Generate coverage analysis
      run: cmake --build ${{github.workspace}}/build/code-coverage --target coverage
